// Auto-generated TypeScript types from database schema
// DO NOT EDIT MANUALLY - This file is generated by generate_database_types tool

export interface CallRecordingsS622Aa9440Row {
  id: number;
  corp_id: string | null;
  call_id: number;
  file_name: string | null;
  file_url: string | null;
  file_size: number | null;
  duration: number | null;
  format: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type CallRecordingsS622Aa9440Insert = Omit<CallRecordingsS622Aa9440Row, 'id' | 'corp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type CallRecordingsS622Aa9440Update = Partial<CallRecordingsS622Aa9440Insert>;

export interface CallsS622Aa9440Row {
  id: number;
  corp_id: string | null;
  campaign_id: number;
  customer_id: number;
  phone: string;
  status: string | null;
  outcome: string | null;
  started_at: string | null;
  ended_at: string | null;
  duration: number | null;
  transcript: string | null;
  ai_summary: string | null;
  customer_sentiment: string | null;
  follow_up_required: boolean | null;
  retry_count: number | null;
  recording_url: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type CallsS622Aa9440Insert = Omit<CallsS622Aa9440Row, 'id' | 'corp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type CallsS622Aa9440Update = Partial<CallsS622Aa9440Insert>;

export interface CampaignCustomersS622Aa9440Row {
  id: number;
  corp_id: string | null;
  campaign_id: number;
  customer_id: number;
  call_status: string | null;
  call_id: number | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type CampaignCustomersS622Aa9440Insert = Omit<CampaignCustomersS622Aa9440Row, 'id' | 'corp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type CampaignCustomersS622Aa9440Update = Partial<CampaignCustomersS622Aa9440Insert>;

export interface CampaignsS622Aa9440Row {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  name: string;
  description: string | null;
  status: string | null;
  voice_agent_id: number | null;
  language: string | null;
  time_window_start: string | null;
  time_window_end: string | null;
  max_retry_attempts: number | null;
  calls_per_minute: number | null;
  caller_id: string | null;
  scheduled_at: string | null;
  started_at: string | null;
  completed_at: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type CampaignsS622Aa9440Insert = Omit<CampaignsS622Aa9440Row, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type CampaignsS622Aa9440Update = Partial<CampaignsS622Aa9440Insert>;

export interface CustomersS622Aa9440Row {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  name: string;
  phone: string;
  order_id: string;
  order_status: string;
  delivery_date: string | null;
  courier_name: string | null;
  tracking_number: string | null;
  language: string | null;
  city: string | null;
  amount: number | null;
  notes: string | null;
  validation_status: string | null;
  validation_errors: Record<string, unknown> | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type CustomersS622Aa9440Insert = Omit<CustomersS622Aa9440Row, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type CustomersS622Aa9440Update = Partial<CustomersS622Aa9440Insert>;

export interface VoiceAgentsS622Aa9440Row {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  name: string;
  description: string | null;
  voice_type: string | null;
  voice_accent: string | null;
  language: string | null;
  greeting_script: string | null;
  main_script: string | null;
  faq_responses: Record<string, unknown> | null;
  company_name: string | null;
  is_active: boolean | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type VoiceAgentsS622Aa9440Insert = Omit<VoiceAgentsS622Aa9440Row, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type VoiceAgentsS622Aa9440Update = Partial<VoiceAgentsS622Aa9440Insert>;
